### PR TITLE
Kendrick fx

### PR DESCRIPTION
**Pull request by ansgarkorf**
Hey Tomas,
javaFXing for the Kendrick Module is done. The feature overview window doesnt work completely. We have to finish the spectra plot first.
Maybe I have time to do Van-Krevelen tomorrow.
Any other modules I can do?
best wishes,
Ansgar

### CODE REVIEW

**Comment by ansgarkorf** [comment]
KendrickFX

**Comment by tomas-pluskal** [comment]
Hi Ansgar,

This is great work, and sorry for responding so late - for some reason I didn't receive any email notification about these PRs from github, so I only noticed them now! There is a minor conflict in the parameter class, so once you resolve the conflict I'll be happy to merge this.

**Comment by ansgarkorf** [comment]
all done

**Comment by tomas-pluskal** [comment]
Awesome, thanks!

**Pull request merged**
